_wandb:
    value:
        cli_version: 0.19.10
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 5
                - 6
                - 53
                - 55
            "2":
                - 5
                - 6
                - 53
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.10
            "8":
                - 5
            "12": 0.19.10
            "13": linux-x86_64
features:
    value:
        - gait_speed
        - steps
        - awakenings
        - bedexitcount
        - end_sleep_time
        - inbed_time
        - outbed_time
        - sleepscore
        - durationinsleep
        - durationawake
        - waso
        - hrvscore
        - start_sleep_time
        - time_to_sleep
        - time_in_bed_after_sleep
        - total_time_in_bed
        - tossnturncount
        - sleep_period
        - minhr
        - maxhr
        - avghr
        - avgrr
        - maxrr
        - minrr
        - steps_norm
        - steps_delta
        - steps_delta_1d
        - steps_ma_7
        - gait_speed_norm
        - gait_speed_delta
        - gait_speed_delta_1d
        - gait_speed_ma_7
        - awakenings_norm
        - awakenings_delta
        - awakenings_delta_1d
        - awakenings_ma_7
        - bedexitcount_norm
        - bedexitcount_delta
        - bedexitcount_delta_1d
        - bedexitcount_ma_7
        - end_sleep_time_norm
        - end_sleep_time_delta
        - end_sleep_time_delta_1d
        - end_sleep_time_ma_7
        - inbed_time_norm
        - inbed_time_delta
        - inbed_time_delta_1d
        - inbed_time_ma_7
        - outbed_time_norm
        - outbed_time_delta
        - outbed_time_delta_1d
        - outbed_time_ma_7
        - sleepscore_norm
        - sleepscore_delta
        - sleepscore_delta_1d
        - sleepscore_ma_7
        - durationinsleep_norm
        - durationinsleep_delta
        - durationinsleep_delta_1d
        - durationinsleep_ma_7
        - durationawake_norm
        - durationawake_delta
        - durationawake_delta_1d
        - durationawake_ma_7
        - waso_norm
        - waso_delta
        - waso_delta_1d
        - waso_ma_7
        - hrvscore_norm
        - hrvscore_delta
        - hrvscore_delta_1d
        - hrvscore_ma_7
        - start_sleep_time_norm
        - start_sleep_time_delta
        - start_sleep_time_delta_1d
        - start_sleep_time_ma_7
        - time_to_sleep_norm
        - time_to_sleep_delta
        - time_to_sleep_delta_1d
        - time_to_sleep_ma_7
        - time_in_bed_after_sleep_norm
        - time_in_bed_after_sleep_delta
        - time_in_bed_after_sleep_delta_1d
        - time_in_bed_after_sleep_ma_7
        - total_time_in_bed_norm
        - total_time_in_bed_delta
        - total_time_in_bed_delta_1d
        - total_time_in_bed_ma_7
        - tossnturncount_norm
        - tossnturncount_delta
        - tossnturncount_delta_1d
        - tossnturncount_ma_7
        - sleep_period_norm
        - sleep_period_delta
        - sleep_period_delta_1d
        - sleep_period_ma_7
        - minhr_norm
        - minhr_delta
        - minhr_delta_1d
        - minhr_ma_7
        - maxhr_norm
        - maxhr_delta
        - maxhr_delta_1d
        - maxhr_ma_7
        - avghr_norm
        - avghr_delta
        - avghr_delta_1d
        - avghr_ma_7
        - avgrr_norm
        - avgrr_delta
        - avgrr_delta_1d
        - avgrr_ma_7
        - maxrr_norm
        - maxrr_delta
        - maxrr_delta_1d
        - maxrr_ma_7
        - minrr_norm
        - minrr_delta
        - minrr_delta_1d
        - minrr_ma_7
        - days_since_fall
        - days_until_fall
        - days_since_hospital
        - days_until_hospital
imputer:
    value: vae
label_shift_days:
    value: 7
model:
    value: XGboost
